// This file is automatically generated. Do not edit it directly.
//
// Kept (issue #66): not Lovable-only scaffolding - `src/start.ts` registers
// `attachSupabaseAuth` as global `functionMiddleware`, so every `createServerFn`
// call gets the user's bearer token attached automatically. No route currently
// calls `createServerFn`, so this middleware doesn't fire yet, but removing the
// file would mean editing `start.ts`'s live bootstrap wiring, which is outside
// this issue - deleting it now would silently break auth for the first server
// function a future issue adds.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
