/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBracketsNewRouteImport } from './routes/_authenticated/brackets.new'
import { Route as BracketsBracketIdIndexRouteImport } from './routes/brackets.$bracketId.index'
import { Route as BracketsBracketIdTreeRouteImport } from './routes/brackets.$bracketId.tree'
import { Route as AuthenticatedBracketsBracketIdEditRouteImport } from './routes/_authenticated/brackets.$bracketId.edit'
import { Route as BracketsBracketIdMatchupsMatchupIdIndexRouteImport } from './routes/brackets.$bracketId.matchups.$matchupId.index'
import { Route as BracketsBracketIdMatchupsMatchupIdResultRouteImport } from './routes/brackets.$bracketId.matchups.$matchupId.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBracketsNewRoute =
  AuthenticatedBracketsNewRouteImport.update({
    id: '/brackets/new',
    path: '/brackets/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BracketsBracketIdIndexRoute = BracketsBracketIdIndexRouteImport.update({
  id: '/brackets/$bracketId/',
  path: '/brackets/$bracketId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BracketsBracketIdTreeRoute = BracketsBracketIdTreeRouteImport.update({
  id: '/brackets/$bracketId/tree',
  path: '/brackets/$bracketId/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBracketsBracketIdEditRoute =
  AuthenticatedBracketsBracketIdEditRouteImport.update({
    id: '/brackets/$bracketId/edit',
    path: '/brackets/$bracketId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BracketsBracketIdMatchupsMatchupIdIndexRoute =
  BracketsBracketIdMatchupsMatchupIdIndexRouteImport.update({
    id: '/brackets/$bracketId/matchups/$matchupId/',
    path: '/brackets/$bracketId/matchups/$matchupId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BracketsBracketIdMatchupsMatchupIdResultRoute =
  BracketsBracketIdMatchupsMatchupIdResultRouteImport.update({
    id: '/brackets/$bracketId/matchups/$matchupId/result',
    path: '/brackets/$bracketId/matchups/$matchupId/result',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/brackets/new': typeof AuthenticatedBracketsNewRoute
  '/brackets/$bracketId/tree': typeof BracketsBracketIdTreeRoute
  '/brackets/$bracketId/': typeof BracketsBracketIdIndexRoute
  '/brackets/$bracketId/edit': typeof AuthenticatedBracketsBracketIdEditRoute
  '/brackets/$bracketId/matchups/$matchupId/result': typeof BracketsBracketIdMatchupsMatchupIdResultRoute
  '/brackets/$bracketId/matchups/$matchupId/': typeof BracketsBracketIdMatchupsMatchupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/brackets/new': typeof AuthenticatedBracketsNewRoute
  '/brackets/$bracketId/tree': typeof BracketsBracketIdTreeRoute
  '/brackets/$bracketId': typeof BracketsBracketIdIndexRoute
  '/brackets/$bracketId/edit': typeof AuthenticatedBracketsBracketIdEditRoute
  '/brackets/$bracketId/matchups/$matchupId/result': typeof BracketsBracketIdMatchupsMatchupIdResultRoute
  '/brackets/$bracketId/matchups/$matchupId': typeof BracketsBracketIdMatchupsMatchupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/brackets/new': typeof AuthenticatedBracketsNewRoute
  '/brackets/$bracketId/tree': typeof BracketsBracketIdTreeRoute
  '/brackets/$bracketId/': typeof BracketsBracketIdIndexRoute
  '/_authenticated/brackets/$bracketId/edit': typeof AuthenticatedBracketsBracketIdEditRoute
  '/brackets/$bracketId/matchups/$matchupId/result': typeof BracketsBracketIdMatchupsMatchupIdResultRoute
  '/brackets/$bracketId/matchups/$matchupId/': typeof BracketsBracketIdMatchupsMatchupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/dashboard'
    | '/brackets/new'
    | '/brackets/$bracketId/tree'
    | '/brackets/$bracketId/'
    | '/brackets/$bracketId/edit'
    | '/brackets/$bracketId/matchups/$matchupId/result'
    | '/brackets/$bracketId/matchups/$matchupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/dashboard'
    | '/brackets/new'
    | '/brackets/$bracketId/tree'
    | '/brackets/$bracketId'
    | '/brackets/$bracketId/edit'
    | '/brackets/$bracketId/matchups/$matchupId/result'
    | '/brackets/$bracketId/matchups/$matchupId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/discover'
    | '/_authenticated/dashboard'
    | '/_authenticated/brackets/new'
    | '/brackets/$bracketId/tree'
    | '/brackets/$bracketId/'
    | '/_authenticated/brackets/$bracketId/edit'
    | '/brackets/$bracketId/matchups/$matchupId/result'
    | '/brackets/$bracketId/matchups/$matchupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  BracketsBracketIdTreeRoute: typeof BracketsBracketIdTreeRoute
  BracketsBracketIdIndexRoute: typeof BracketsBracketIdIndexRoute
  BracketsBracketIdMatchupsMatchupIdResultRoute: typeof BracketsBracketIdMatchupsMatchupIdResultRoute
  BracketsBracketIdMatchupsMatchupIdIndexRoute: typeof BracketsBracketIdMatchupsMatchupIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brackets/new': {
      id: '/_authenticated/brackets/new'
      path: '/brackets/new'
      fullPath: '/brackets/new'
      preLoaderRoute: typeof AuthenticatedBracketsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/brackets/$bracketId/': {
      id: '/brackets/$bracketId/'
      path: '/brackets/$bracketId'
      fullPath: '/brackets/$bracketId/'
      preLoaderRoute: typeof BracketsBracketIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brackets/$bracketId/tree': {
      id: '/brackets/$bracketId/tree'
      path: '/brackets/$bracketId/tree'
      fullPath: '/brackets/$bracketId/tree'
      preLoaderRoute: typeof BracketsBracketIdTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/brackets/$bracketId/edit': {
      id: '/_authenticated/brackets/$bracketId/edit'
      path: '/brackets/$bracketId/edit'
      fullPath: '/brackets/$bracketId/edit'
      preLoaderRoute: typeof AuthenticatedBracketsBracketIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/brackets/$bracketId/matchups/$matchupId/': {
      id: '/brackets/$bracketId/matchups/$matchupId/'
      path: '/brackets/$bracketId/matchups/$matchupId'
      fullPath: '/brackets/$bracketId/matchups/$matchupId/'
      preLoaderRoute: typeof BracketsBracketIdMatchupsMatchupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brackets/$bracketId/matchups/$matchupId/result': {
      id: '/brackets/$bracketId/matchups/$matchupId/result'
      path: '/brackets/$bracketId/matchups/$matchupId/result'
      fullPath: '/brackets/$bracketId/matchups/$matchupId/result'
      preLoaderRoute: typeof BracketsBracketIdMatchupsMatchupIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedBracketsNewRoute: typeof AuthenticatedBracketsNewRoute
  AuthenticatedBracketsBracketIdEditRoute: typeof AuthenticatedBracketsBracketIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedBracketsNewRoute: AuthenticatedBracketsNewRoute,
  AuthenticatedBracketsBracketIdEditRoute:
    AuthenticatedBracketsBracketIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  BracketsBracketIdTreeRoute: BracketsBracketIdTreeRoute,
  BracketsBracketIdIndexRoute: BracketsBracketIdIndexRoute,
  BracketsBracketIdMatchupsMatchupIdResultRoute:
    BracketsBracketIdMatchupsMatchupIdResultRoute,
  BracketsBracketIdMatchupsMatchupIdIndexRoute:
    BracketsBracketIdMatchupsMatchupIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
